'''
Penny-shaped Crack Solution from Fialko et al 2001
'''
# Autogenerated with SMOP version 0.22
# /Users/scott/Library/Enthought/Canopy_64bit/User/bin/smop -v calc_okada.m -o calc_okada.py
from __future__ import division
import numpy as np
import matplotlib.pyplot as plt
#import roipy as rp
#import examples